# Generated by Django 5.0.1 on 2024-05-29 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='gps',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zipcode',
            new_name='region',
        ),
    ]
